### ISSUE TITLE
Error: Invalid Configuration

### ISSUE THREAD

**Issue by sdymj84** [cuplefashion/cuplefashion#4]
I cloned project from my repository and run it by "node keystone" and got below error messages.
Did you happen to see these error when you clone and run on you linux PC?

-----------------------------------------------------------------------------------
/home/minjun1.y/Web-Development/cuplefashion/node_modules/keystone/fields/types/cloudinaryimage/CloudinaryImageType.js:59
                throw new Error(
                ^

Error: Invalid Configuration

CloudinaryImage fields (Gallery.heroImage) require the "cloudinary config" option to be set.

See http://keystonejs.com/docs/configuration/#services-cloudinary for more information.

    at new cloudinaryimage (/home/minjun1.y/Web-Development/cuplefashion/node_modules/keystone/fields/types/cloudinaryimage/CloudinaryImageType.js:59:9)
    at List.field (/home/minjun1.y/Web-Development/cuplefashion/node_modules/keystone/lib/list/field.js:45:14)
    at List.<anonymous> (/home/minjun1.y/Web-Development/cuplefashion/node_modules/keystone/lib/list/add.js:41:16)
    at List.<anonymous> (/home/minjun1.y/Web-Development/cuplefashion/node_modules/keystone/lib/list/add.js:30:5)
    at /home/minjun1.y/Web-Development/cuplefashion/node_modules/keystone/lib/list/add.js:74:5
    at arrayEach (/home/minjun1.y/Web-Development/cuplefashion/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/home/minjun1.y/Web-Development/cuplefashion/node_modules/lodash/lodash.js:9344:14)
    at List.add (/home/minjun1.y/Web-Development/cuplefashion/node_modules/keystone/lib/list/add.js:48:4)
    at Object.<anonymous> (/home/minjun1.y/Web-Development/cuplefashion/models/Gallery.js:13:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)

**Comment by byul5810** [comment]
Create env file in your root folder and save your Cloudinaryimage URL. This is because GitHub block to upload your pirvate information from your local files.
